### ISSUE TITLE
Architecture - Update current Architecture diagrams

### ISSUE THREAD

**Issue by MarcAndreDubuc** [MarcAndreDubuc/Canadian-Climate-Data-Portal-2#41]
See confluence diagrams: https://ccdpwiki.atlassian.net/wiki/spaces/CCDP/pages/11698217/Diagrams

To be completed before Sept 10.

**Comment by MarcAndreDubuc** [comment]
Update made by Mathieu Provencher : https://ccdpwiki.atlassian.net/wiki/spaces/CCDP/pages/137035777/Components+Localisation+Diagram

**Comment by dbyrns** [comment]
Sequence diagrams for heat wave and daily download have been update by Mathieu too : 
https://ccdpwiki.atlassian.net/wiki/spaces/CCDP/pages/11698217/Diagrams
